// smithy-config.h - Runtime shape-specific MMVQ kernel config for kernel-anvil
//
// Loads per-model kernel configs from JSON at first dispatch.
// Generated by: kernel-anvil gguf-optimize model.gguf
// Docs: https://github.com/apollosenvy/kernel-anvil
//
// Config path (checked in order):
//   1. SMITHY_CONFIG env var (explicit path to config JSON)
//   2. ~/.cache/smithy/<model_stem>.json (requires smithy_set_model() or SMITHY_MODEL env var)
//   3. ~/.cache/smithy/default.json (fallback)
//
// Format:
//   { "configs": { "<type_idx>": { "<n_bucket>,<k_bucket>": {"nwarps": N, "rows_per_block": R} } } }

#pragma once

#include <cstdio>
#include <cstdlib>
#include <cstring>

// GGML_TYPE_COUNT is defined in ggml.h when included inside a llama.cpp build.
// Fallback for standalone compilation or static analysis.
#ifndef GGML_TYPE_COUNT
#define GGML_TYPE_COUNT 41
#endif

enum smithy_bucket : int {
    SMITHY_BUCKET_LE_128   = 0,
    SMITHY_BUCKET_LE_1024  = 1,
    SMITHY_BUCKET_LE_4096  = 2,
    SMITHY_BUCKET_LE_16384 = 3,
    SMITHY_BUCKET_GT_16384 = 4,
    SMITHY_NUM_BUCKETS     = 5,
};

struct smithy_shape_config {
    int nwarps;         // 0 = use default
    int rows_per_block; // 0 = use default
};

static inline smithy_bucket smithy_get_bucket(int dim) {
    if (dim <= 128)   return SMITHY_BUCKET_LE_128;
    if (dim <= 1024)  return SMITHY_BUCKET_LE_1024;
    if (dim <= 4096)  return SMITHY_BUCKET_LE_4096;
    if (dim <= 16384) return SMITHY_BUCKET_LE_16384;
    return SMITHY_BUCKET_GT_16384;
}

static smithy_shape_config smithy_configs[GGML_TYPE_COUNT][SMITHY_NUM_BUCKETS][SMITHY_NUM_BUCKETS] = {};
static bool smithy_configs_loaded  = false;
static bool smithy_load_attempted  = false;
static char smithy_model_path[512] = {};

// Call this when loading a model so smithy can find model-specific configs.
// path: full path to the GGUF file (e.g., "/home/user/models/Qwen3-8B-Q4_K_M.gguf")
static void smithy_set_model(const char * path) {
    if (!path) return;
    size_t len = strlen(path);
    if (len >= sizeof(smithy_model_path)) len = sizeof(smithy_model_path) - 1;
    memcpy(smithy_model_path, path, len);
    smithy_model_path[len] = '\0';
    // Reset load state so the next lookup picks up the model-specific config
    smithy_configs_loaded = false;
    smithy_load_attempted = false;
    memset(smithy_configs, 0, sizeof(smithy_configs));
}

static bool smithy_load_configs(const char * path) {
    FILE * f = fopen(path, "r");
    if (!f) return false;

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (size <= 0 || size > 1024 * 1024) { fclose(f); return false; }

    char * buf = (char *)malloc(size + 1);
    if (!buf) { fclose(f); return false; }
    size_t nread = fread(buf, 1, size, f);
    fclose(f);
    buf[nread] = '\0';

    int loaded = 0;
    const char * p = strstr(buf, "\"configs\"");
    if (!p) { free(buf); return false; }

    while ((p = strchr(p, '"')) != NULL) {
        p++;
        int type_idx = -1;
        if (*p >= '0' && *p <= '9') {
            type_idx = atoi(p);
            p = strchr(p, '{');
            if (!p || type_idx < 0 || type_idx >= GGML_TYPE_COUNT) continue;

            const char * type_end = NULL;
            int depth = 1;
            const char * scan = p + 1;
            while (*scan && depth > 0) {
                if (*scan == '{') depth++;
                if (*scan == '}') depth--;
                if (depth == 0) { type_end = scan; break; }
                scan++;
            }
            if (!type_end) break;

            const char * entry = p;
            while (entry < type_end) {
                entry = strchr(entry, '"');
                if (!entry || entry >= type_end) break;
                entry++;

                int nb = -1, kb = -1;
                if (sscanf(entry, "%d,%d", &nb, &kb) == 2 &&
                    nb >= 0 && nb < SMITHY_NUM_BUCKETS &&
                    kb >= 0 && kb < SMITHY_NUM_BUCKETS) {

                    const char * nw_key  = strstr(entry, "\"nwarps\"");
                    const char * rpb_key = strstr(entry, "\"rows_per_block\"");
                    if (nw_key && nw_key < type_end && rpb_key && rpb_key < type_end) {
                        int nw = 0, rpb = 0;
                        const char * nw_val  = strchr(nw_key + 8, ':');
                        const char * rpb_val = strchr(rpb_key + 16, ':');
                        if (nw_val)  nw  = atoi(nw_val + 1);
                        if (rpb_val) rpb = atoi(rpb_val + 1);
                        if (nw > 0 && nw <= 32 && rpb > 0 && rpb <= 32) {
                            smithy_configs[type_idx][nb][kb] = {nw, rpb};
                            loaded++;
                        }
                    }
                }
                entry++;
            }
            p = type_end + 1;
        }
    }

    free(buf);
    smithy_configs_loaded = (loaded > 0);
    if (smithy_configs_loaded) {
        fprintf(stderr, "kernel-anvil: loaded %d shape configs from %s\n", loaded, path);
    }
    return smithy_configs_loaded;
}

static void smithy_try_load() {
    if (smithy_configs_loaded || smithy_load_attempted) return;
    smithy_load_attempted = true;

    // Priority 1: SMITHY_CONFIG env var (explicit path)
    const char * env_path = getenv("SMITHY_CONFIG");
    if (env_path && smithy_load_configs(env_path)) return;

    const char * home = getenv("HOME");
    if (!home) return;

    // Priority 2: ~/.cache/smithy/<model_stem>.json (model-specific)
    // Model path source: smithy_set_model() API or SMITHY_MODEL env var.
    const char * model_src = smithy_model_path;
    const char * env_model = getenv("SMITHY_MODEL");
    if (smithy_model_path[0] == '\0' && env_model) {
        model_src = env_model;
    }
    if (model_src[0] != '\0') {
        // Extract stem: find last '/' then strip extension
        const char * base = strrchr(model_src, '/');
        if (!base) base = strrchr(model_src, '\\');
        base = base ? base + 1 : model_src;

        char stem[256];
        size_t stem_len = strlen(base);
        const char * dot = strrchr(base, '.');
        if (dot && dot > base) stem_len = (size_t)(dot - base);
        if (stem_len >= sizeof(stem)) stem_len = sizeof(stem) - 1;
        memcpy(stem, base, stem_len);
        stem[stem_len] = '\0';

        char model_path[512];
        snprintf(model_path, sizeof(model_path), "%s/.cache/smithy/%s.json", home, stem);
        if (smithy_load_configs(model_path)) return;
    }

    // Priority 3: ~/.cache/smithy/default.json (fallback)
    char default_path[512];
    snprintf(default_path, sizeof(default_path), "%s/.cache/smithy/default.json", home);
    smithy_load_configs(default_path);
}

static inline smithy_shape_config smithy_lookup(int type_idx, int nrows, int ncols) {
    smithy_try_load();
    if (!smithy_configs_loaded || type_idx < 0 || type_idx >= GGML_TYPE_COUNT) {
        return {0, 0};
    }
    return smithy_configs[type_idx][smithy_get_bucket(nrows)][smithy_get_bucket(ncols)];
}
